### PR TITLE
fixed stupid problems

### PR DESCRIPTION
**Pull request by Daniil-Y**

### CODE REVIEW

**Review by Pankin610 — APPROVED** [review]
nice code bro, looks good to me

**Comment by FiIipson** [comment]
Is it just me or code is not interpreted by IDE without `.java` extension? :disappointed:

**Comment by Pankin610** [comment]
> Is it just me or code is not interpreted by IDE without `.java` extension? 😞

Daniel added the extension in this pull request

**Comment by FiIipson** [comment]
> > Is it just me or code is not interpreted by IDE without `.java` extension? disappointed
> 
> Daniel added the extension in this pull request

Right, the fault is on mine

**Review by FiIipson — APPROVED** [review]
looks good

**Pull request merged**
